### ISSUE TITLE
`make install` fails

### ISSUE THREAD

**Issue by crystalattice** [networkop/meshnet-cni#33]
Going through the README demo, I get to the point of running `make install` but it fails to execute

`popos@pop-os:~/meshnet-cni$ make install
/home/popos/go/bin/kind load docker-image --name "meshnet" networkop/meshnet:4bf3db7-dirty
Image: "networkop/meshnet:4bf3db7-dirty" with ID "sha256:8eaa415b1910d98d19dad3a6396c85893e27e40f8842ed6a1c9a47e27962d293" not yet present on node "meshnet-control-plane", loading...
Image: "networkop/meshnet:4bf3db7-dirty" with ID "sha256:8eaa415b1910d98d19dad3a6396c85893e27e40f8842ed6a1c9a47e27962d293" not yet present on node "meshnet-worker", loading...
Image: "networkop/meshnet:4bf3db7-dirty" with ID "sha256:8eaa415b1910d98d19dad3a6396c85893e27e40f8842ed6a1c9a47e27962d293" not yet present on node "meshnet-worker3", loading...
Image: "networkop/meshnet:4bf3db7-dirty" with ID "sha256:8eaa415b1910d98d19dad3a6396c85893e27e40f8842ed6a1c9a47e27962d293" not yet present on node "meshnet-worker2", loading...
ERROR: command "docker save -o /tmp/images-tar964290207/images.tar networkop/meshnet:4bf3db7-dirty" failed with error: exit status 1
Command Output: failed to save image: invalid output path: directory "/tmp/images-tar964290207" does not exist
make: *** [.mk/kind.mk:33: kind-load] Error 1
`

I have tried this on clean VMs of both Ubuntu 21.04 and 21.10.

**Comment by crystalattice** [comment]
A coworker was able to successfully run `make install` using macOS, so maybe it's how Linux handles the call.

**Comment by networkop** [comment]
this looks strange. can you confirm you can see the `networkop/meshnet:4bf3db7-dirty` image in your local registry?

**Comment by crystalattice** [comment]
Unless there is something else I should be looking at, it appears to be there
![Screenshot from 2021-12-15 08-43-29](https://user-images.githubusercontent.com/5722904/146207369-8f768ec6-7636-4bd5-84cf-c8778d920b8d.png)
.

**Comment by networkop** [comment]
seems like you may be hitting [this issue](https://github.com/kubernetes-sigs/kind/issues/2535#issuecomment-968836159)?
are you installing docker from snap? can you try the suggested workaround, i.e. passing TMPDIR env variable to `kind load` command?

**Comment by crystalattice** [comment]
Yes, I'm using docker from snap. Thanks for the info; I wasn't aware this was a problem.

I'll change my settings and continue; I will also close this issue.
