### ISSUE TITLE
Can meshnet-cni support the SDN?

### ISSUE THREAD

**Issue by cse578group29** [networkop/meshnet-cni#34]
Hello, meshenet-cni can support the network created by k8s-topo well.  Can it support the SDN (e.g., created by Mininet)? Is there an example?  Thank you!

**Comment by networkop** [comment]
meshnet-cni was only designed to be used as a Kubernetes CNI plugin. Anything else is outside of scope.

**Comment by cse578group29** [comment]
Thank you!
