### ISSUE TITLE
Ablity to choose a specific NIC for VXLAN bind 

### ISSUE THREAD

**Issue by sar772004** [networkop/meshnet-cni#71]
Problem:
Way to define specific port on the compute to carry the VXLAN traffic.  

Issue:
Currently, I am trying to achieve the MTU of vxlan bind atleast 9232.

By the way it seems the MTU currently is being picked from the underlying interface and its being tied to the primary address as defined here.
https://github.com/networkop/meshnet-cni/blob/master/manifests/base/daemonset.yaml#L41

We want to use a specific NIC for carrying the vxlan binds. and i m not finding a way to define the endpoint IP to be picked up from a specific interface on the computes.

Any idea how i can point to a specific underlay interface for the VXLAN binds to use ?
Once i have the chosen interface(which supports larger MTU)  i could have a large MTU on that and probably proceed.

Also this allows us to control entire meshnet traffic on a specific interface rather than on the k8s control/mgmt port.

**Comment by sar772004** [comment]
> I see what you mean. This is currently not implemented, although it doesn't seem like it would be too difficult a change. e.g. HOST_INTF variable that would have some tie-breaking logic with HOST_IP.

Thanks that will be really useful change

**Comment by sar772004** [comment]
+ @kingshukdev (he may have added this code)
It seems we may have issue in plugin/meshnet.go getVxlanSource, it goes through the net.Interfaces list ( but that is routing information) , So it seems to use the default route gateway instead of the nodeIP even that is passed in with HOST_IP environment in the daemonset.yml.

Can you please check this ?

**Comment by kingshukdev** [comment]
@sar772004 - trying to understand first what you tried : 

- name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

in daemon set yaml, in place of valueFrom you have give the "value" of HOST_IP directly ? 

Note :- unless your two pods are hosted in two different K8S node, there will not be any VxLAN between them. If K8S deploy the pods in the same node, then they have vEth pair between them. In these two cases the interface MTUs are different. 
This causes unpredictability in MTU as it depends on how pods are deployed. 

If your core requirement is :-
- Have predictable MTU and configurable. 
- Have MTU > 1500
I am hoping I will have some cycle in 2nd half of April to explore these two.

**Comment by sar772004** [comment]
> @sar772004 - trying to understand first what you tried :
> 
> * name: HOST_IP
>   valueFrom:
>   fieldRef:
>   fieldPath: status.hostIP
> 
> in daemon set yaml, in place of valueFrom you have give the "value" of HOST_IP directly ?
> 
> Note :- unless your two pods are hosted in two different K8S node, there will not be any VxLAN between them. If K8S deploy the pods in the same node, then they have vEth pair between them. In these two cases the interface MTUs are different. This causes unpredictability in MTU as it depends on how pods are deployed.
> 
> If your core requirement is :-
> 
> * Have predictable MTU and configurable.
> * Have MTU > 1500
>   I am hoping I will have some cycle in 2nd half of April to explore these two.

My setup is with 4 nodes connected via breth2 ( 5.2.1.0/24 subnet)

I had tried hardcoding the host_ip in yaml, but that leads to this error when the pod is schedule on another node
```
  Warning  FailedCreatePodSandBox  29s (x11 over 8m21s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f1cf1f4f41b83c7e84d690c33b78348b813943a62eca3de48180586def9a90fd" network for pod "dut-a": networkPlugin cni failed to set up pod "dut-a_default" network: no iface found for address 5.2.1.1
```

You are right, those are my core requirements. But its not just MTU, selecting of interface allows more control on where the data path traffic goes.

To achieve status.NodeIP in daemonset.yaml fetch the breth2 IP, i switched my k8s init to use the 5.2 network like this "kubeadm init --apiserver-advertise-address ${breth2IP} .. rest of args"

(HYP-1-HOST):~ > kubectl get nodes  -o wide
NAME                                    STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                           KERNEL-VERSION                 CONTAINER-RUNTIME
hyp-1.xyx.com   Ready    control-plane   21m   v1.25.0   5.2.1.1       <none>        Rocky Linux 8.7 (Green Obsidian)   4.18.0-425.13.1.el8_7.x86_64   docker://20.10.22
hyp-2.xyz.com   Ready    <none>          21m   v1.25.0   5.2.1.2       <none>        Rocky Linux 8.7 (Green Obsidian)   4.18.0-425.13.1.el8_7.x86_64   docker://20.10.22
hyp-3.xyz.com   Ready    <none>          20m   v1.25.0   5.2.1.3       <none>        Rocky Linux 8.7 (Green Obsidian)   4.18.0-425.13.1.el8_7.x86_64   docker://20.10.22
hyp-4.xyz.com   Ready    <none>          20m   v1.25.0   5.2.1.4       <none>        Rocky Linux 8.7 (Green Obsidian)   4.18.0-425.13.1.el8_7.x86_64   docker://20.10.22

**Comment by sar772004** [comment]
I m novice with go, so excuse any mistakes, but based on @networkop comment, we could add HOST_INTF env to make this more deterministic. i have some changes, but not very sure how to try this locally. Just building the meshnet docker image and changing reference in base/daemonset.yaml should be good ?

diff --git a/daemon/meshnet/handler.go b/daemon/meshnet/handler.go
index ccefd57..571de62 100644
--- a/daemon/meshnet/handler.go
+++ b/daemon/meshnet/handler.go
@@ -64,6 +64,7 @@ func (m *Meshnet) Get(ctx context.Context, pod *mpb.PodQuery) (*mpb.Pod, error)
        srcIP, _, _ := unstructured.NestedString(result.Object, "status", "src_ip")
        netNs, _, _ := unstructured.NestedString(result.Object, "status", "net_ns")
        nodeIP := os.Getenv("HOST_IP")
+       NodeIntf := os.Getenv("HOST_INTF")
 
        return &mpb.Pod{
                Name:   pod.Name,
@@ -72,6 +73,7 @@ func (m *Meshnet) Get(ctx context.Context, pod *mpb.PodQuery) (*mpb.Pod, error)
                KubeNs: pod.KubeNs,
                Links:  links,
                NodeIp: nodeIP,
+               NodeIntf: nodeIntf,
        }, nil
 }
 
diff --git a/daemon/proto/meshnet/v1beta1/meshnet.pb.go b/daemon/proto/meshnet/v1beta1/meshnet.pb.go
index 49dd15d..5db0039 100644
--- a/daemon/proto/meshnet/v1beta1/meshnet.pb.go
+++ b/daemon/proto/meshnet/v1beta1/meshnet.pb.go
@@ -31,6 +31,7 @@ type Pod struct {
        KubeNs string  `protobuf:"bytes,4,opt,name=kube_ns,json=kubeNs,proto3" json:"kube_ns,omitempty"`
        Links  []*Link `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
        NodeIp string  `protobuf:"bytes,6,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
+       NodeIntf string  `protobuf:"bytes,6,opt,name=node_intf,json=nodeIntf,proto3" json:"node_intf,omitempty"`
 }
 
 func (x *Pod) Reset() {
diff --git a/daemon/proto/meshnet/v1beta1/meshnet.proto b/daemon/proto/meshnet/v1beta1/meshnet.proto
index dbe46ab..a24a1da 100644
--- a/daemon/proto/meshnet/v1beta1/meshnet.proto
+++ b/daemon/proto/meshnet/v1beta1/meshnet.proto
@@ -12,6 +12,7 @@ message Pod {
   string kube_ns = 4;
   repeated Link links = 5;
   string node_ip = 6;
+  string node_intf = 7;
 }
 
 message Link {
@@ -136,4 +137,4 @@ service Remote {
 service WireProtocol {
   rpc SendToOnce (Packet) returns (BoolResponse);
   rpc SendToStream (stream Packet) returns (BoolResponse);
-}
\ No newline at end of file
+}
diff --git a/plugin/meshnet.go b/plugin/meshnet.go
index 4eb518a..75614d0 100644
--- a/plugin/meshnet.go
+++ b/plugin/meshnet.go
@@ -84,13 +84,13 @@ func loadConf(bytes []byte) (*netConf, *current.Result, error) {
 }
 
 // getVxlanSource uses netlink to get the iface reliably given an IP address.
-func getVxlanSource(nodeIP string) (string, string, error) {
-       if nodeIP == "" {
-               return "", "", fmt.Errorf("meshnetd provided no HOST_IP address: %s", nodeIP)
+func getVxlanSource(nodeIP string, nodeIntf string) (string, string, error) {
+       if nodeIntf == "" && nodeIP == "" {
+               return "", "", fmt.Errorf("meshnetd provided no HOST_IP address: %s or HOST_INTF: %s", nodeIP, nodeIntf)
        }
        nIP := net.ParseIP(nodeIP)
-       if nIP == nil {
-               return "", "", fmt.Errorf("parsing failed for meshnetd provided no HOST_IP address: %s", nodeIP)
+       if nIP == nil && nodeIntf == "" {
+               return "", "", fmt.Errorf("parsing failed for meshnetd provided no HOST_IP address: %s and node HOST_INTF: %s", nodeIP, nodeIntf)
        }
        ifaces, _ := net.Interfaces()
        for _, i := range ifaces {
@@ -103,7 +103,10 @@ func getVxlanSource(nodeIP string) (string, string, error) {
                        case *net.IPAddr:
                                ip = v.IP
                        }
-                       if nIP.Equal(ip) {
+                       if nodeIntf != "":
+                          if i.Name == nodeIntf:
+                              return ip, nodeIntf, nil
+                       if nIP != nil && nIP.Equal(ip) {
                                log.Infof("Found iface %s for address %s", i.Name, nodeIP)
                                return nodeIP, i.Name, nil
                        }
@@ -182,7 +185,7 @@ func cmdAdd(args *skel.CmdArgs) error {
        }
 
        // Finding the source IP and interface for VXLAN VTEP
-       srcIP, srcIntf, err := getVxlanSource(localPod.NodeIp)
+       srcIP, srcIntf, err := getVxlanSource(localPod.NodeIp, localPod.NodeIntf)
        if err != nil {
                return err
        }

**Comment by sar772004** [comment]
Also note that, when this is seen in /var/log/meshnet-cni.log, the eth4 is missing in the pod, so there maybe an issue in this code handling 

time="2023-03-30T16:37:16-07:00" level=info msg="Creating Veth struct with NetNS:/proc/722403/ns/net and intfName: eth4, IP:"
time="2023-03-30T16:37:16-07:00" level=info msg="Pod test is retrieving peer pod dut-a information from meshnet daemon"
time="2023-03-30T16:37:16-07:00" level=info msg="Is peer pod dut-a alive?: false"
time="2023-03-30T16:37:16-07:00" level=info msg=**"Peer pod dut-a isn't alive yet, continuing"**
