### ISSUE TITLE
Add new pod with meshnet

### ISSUE THREAD

**Issue by yennym3** [networkop/meshnet-cni#81]
Hi, 
Would there be a way with meshnet, to add a new pod with a link , to a node of a topology that was already created (The topology was previously created with KNE), without having to destroy or redeploy the topology? 

For example, I am creating this yaml, which uses pod r1 of the topology created in the namespace 2ceos, pod r3 is created, but the links connecting the two pods are not created.
 
<img width="255" alt="image" src="https://github.com/networkop/meshnet-cni/assets/74870040/e7c291ae-881d-4301-912b-bd7ae90c1471">

> kubectl get pods -n 2ceos
<img width="181" alt="image" src="https://github.com/networkop/meshnet-cni/assets/74870040/ed13507e-80d1-46bb-adbc-83d91ebcb293">

> kubectl exec -it r3-0 -n 2ceos -- /bin/sh
<img width="331" alt="image" src="https://github.com/networkop/meshnet-cni/assets/74870040/c00e767e-6cba-4321-a6cf-d3d2e3d4da1b">

**Comment by networkop** [comment]
Nope, this is not possible
